UmbracoConfigurator/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Web.WebApi;

namespace UmbracoConfigurator.Controllers
{
    [PluginController("Umobit")]
    public class ResourcesController : UmbracoApiController
    {
        [HttpGet]//TODO: Make it play
        public FileStreamResult GetResource(string id)
        {
            id = id.Replace("$", "."); //Umbraco routing throws exceptions on using dot
            string resourceName = Assembly.GetExecutingAssembly().GetManifestResourceNames().ToList().FirstOrDefault(f => f.EndsWith(id));

            var resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName);
            var contentType = GetContentType(id);

            var result = new FileStreamResult(resourceStream, contentType);
            return result;
        }

        //public ImageResult GetResource(string id)
        //{
        //    id = id.Replace("$", "."); //Umbraco routing throws exceptions on using dot
        //    string resourceName = Assembly.GetExecutingAssembly().GetManifestResourceNames().ToList().FirstOrDefault(f => f.EndsWith(id));

        //    var resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName);
        //    var contentType = GetContentType(id);

        //    var result = new ImageResult(resourceStream, contentType);
        //    return result;
        //}

        private string GetContentType(string fileId)
        {
            if (fileId.EndsWith(".js"))
            {
                return "text/javascript";
            }
            else if (fileId.EndsWith(".css"))
            {
                return "text/stylesheet";
            }
            else if (fileId.EndsWith(".jpg"))
            {
                return "image/jpeg";
            }
            else if (fileId.EndsWith(".png"))
            {
                return "image/png";
            }
            return "text";
        }
    }

    public class ImageResult : ActionResult
    {
        public ImageResult(Stream imageStream, string contentType)
        {
            if (imageStream == null)
                throw new ArgumentNullException("imageStream");
            if (contentType == null)
                throw new ArgumentNullException("contentType");

            this.ImageStream = imageStream;
            this.ContentType = contentType;
        }

        public Stream ImageStream { get; private set; }
        public string ContentType { get; private set; }

        public override void ExecuteResult(ControllerContext context)
        {
            if (context == null)
                throw new ArgumentNullException("context");

            HttpResponseBase response = context.HttpContext.Response;

            response.ContentType = this.ContentType;

            byte[] buffer = new byte[4096];
            while (true)
            {
                int read = this.ImageStream.Read(buffer, 0, buffer.Length);
                if (read == 0)
                    break;

                response.OutputStream.Write(buffer, 0, read);
            }

            response.End();
        }
    }
}

UmbracoConfigurator/Controllers/UmobitUtilitiesController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.Persistence;
using Umbraco.Core.Persistence.Querying;
using Umbraco.Core.PropertyEditors;
using Umbraco.Core.Services;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Umbraco.Web.PropertyEditors;
using UmbracoConfigurator.Helpers;
using UmbracoConfigurator.Models;

namespace Umobit.UmbracoConfigurator.Controllers
{
    public partial class UmobitUtilitiesController : UmbracoAuthorizedController //SurfaceController
    {


        public ActionResult DocumentTypeUsages(int nodeId)
        {
            List<UsagesModel> usages = new List<UsagesModel>();

            string documentTypeAlias = Services.ContentTypeService.Get(nodeId)?.Alias;

            if (documentTypeAlias.IsNotNullOrEmpty())
            {
                foreach (var root in Umbraco.ContentAtRoot())
                {

                    usages.AddRange(root.DescendantsOrSelf().Where(x => x.ContentType.Alias == documentTypeAlias).Select(x => new UsagesModel() { Id = x.Id, Name = x.Name }));
                    foreach (var node in root.DescendantsOrSelf())
                    {
                        var widgets = node.Properties.Where(x => x.PropertyType.EditorAlias == "Umbraco.NestedContent");
                        if (widgets.Count() > 0)
                        {
                            foreach (var widget in widgets)
                            {
                                var value = widget.Value();
                                if (value is IEnumerable<IPublishedElement>)
                                {
                                    usages.AddRange((value as IEnumerable<IPublishedElement>)
                                          .Where(x => x.ContentType.Alias == documentTypeAlias)
                                          .Select(x => new UsagesModel() { Id = node.Id, Name = node.Name + "(" + widget.Alias + ")" }));
                                }
                                else if (value is IPublishedElement)
                                {
                                    var elem = (value as IPublishedElement);
                                    if (elem.ContentType.Alias == documentTypeAlias)
                                    {
                                        usages.Add(new UsagesModel() { Id = node.Id, Name = node.Name + "(" + widget.Alias + ")" });
                                    }
                                }
                            }
                        }
                    }
                }
            }

            return View(new { Usages = usages, UsagesLinks = string.Join(", ", usages.Select(x => string.Format("<a href=\"{0}\" target=\"_blank\">{1}</a>", x.Link, x.Name))) });
        }










    }




}

UmbracoConfigurator/Views/UmobitUtilities/DocumentTypeUsages.cshtml
@using UmbracoConfigurator.Models


@{
    List<UsagesModel> usages = Model.Usages;
}



<div class="row clearfix dash-row">

    @Html.Raw(Model.UsagesLinks)

</div>

<div class="row clearfix dash-row">
    <div id="result-box" style="background-color: lightgray;padding: 1rem;color: #000;margin-top: 1rem;line-height: 1;border-radius: 5px"></div>
</div>

UmbracoConfigurator/Views/UmobitUtilities/ExportNodeDescendantsToExcelView.cshtml
<style>
    .result-box .success {
        color: forestgreen;
    }

    .result-box .error {
        color: darkred;
    }
    /* Absolute Center Spinner */
    .loading {
        position: fixed;
        z-index: 999;
        height: 2em;
        width: 2em;
        overflow: visible;
        margin: auto;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
    }

        /* Transparent Overlay */
        .loading:before {
            content: '';
            display: block;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.3);
        }

        /* :not(:required) hides these rules from IE9 and below */
        .loading:not(:required) {
            /* hide "loading..." text */
            font: 0/0 a;
            color: transparent;
            text-shadow: none;
            background-color: transparent;
            border: 0;
        }

            .loading:not(:required):after {
                content: '';
                display: block;
                font-size: 10px;
                width: 1em;
                height: 1em;
                margin-top: -0.5em;
                -webkit-animation: spinner 1500ms infinite linear;
                -moz-animation: spinner 1500ms infinite linear;
                -ms-animation: spinner 1500ms infinite linear;
                -o-animation: spinner 1500ms infinite linear;
                animation: spinner 1500ms infinite linear;
                border-radius: 0.5em;
                -webkit-box-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.5) -1.5em 0 0 0, rgba(0, 0, 0, 0.5) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;
                box-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) -1.5em 0 0 0, rgba(0, 0, 0, 0.75) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;
            }

    /* Animation */

    @@-webkit-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @@-moz-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @@-o-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @@keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }
</style>
<div class="loading" id="loader" style="display:none;">Loading&#8230;</div>

<div class="row clearfix dash-row">

    @*<div class="column dash-area" style="display: inline-block;margin-right: 1rem;vertical-align: bottom;">
            <a href="https://www.umobit.com/" target="_blank" class="umobit-logo d-inline-block align-middle ml-2">
                made by&nbsp;<img src="@HtmlHelpers.EmbeddedResource("umobit.png")">
            </a>
        </div>*@
    @*<div class="column dash-area" style="display: inline-block;margin-right: 1rem;vertical-align: bottom;">
            <a href="https://www.umobit.com/" target="_blank" class="umobit-logo d-inline-block align-middle ml-2">
                made by&nbsp;<img src="@Html.Action("GetResource","Resources", new { id = "umobit.png" })">
            </a>
        </div>*@
</div>

<div class="row clearfix dash-row">

    <div id="exportNode-container">
        <input type="hidden" name="exportNode-nodeId" value="@(Model.NodeId)" />
        <div>
            <i>Include self</i>
            <input type="checkbox" name="exportNode-includeSelf" />
        </div>
        <div>
            <i>Include node names</i>
            <input type="checkbox" name="exportNode-includeNodeNames" />
        </div>
        <div>
            <i>Include property names</i>
            <input type="checkbox" name="exportNode-includePropertyNames" />
        </div>
        <br />
        <a id="exportNode-button" target="_blank" href="#" style="display: inline-block;background-color: #ff9900;padding: 1rem;color: #fff;text-decoration:none;margin-top: 1rem;line-height: 1;border-radius: 5px;">Export</a>

    </div>

</div>

<div class="row clearfix dash-row">
    <div id="result-box" style="background-color: lightgray;padding: 1rem;color: #000;margin-top: 1rem;line-height: 1;border-radius: 5px"></div>
</div>


<script>
    $("#exportNode-button").click(function (e) {
        e.preventDefault();
        $("#loader").show();
        var nodeId = $("input[name=exportNode-nodeId]").val();
        var includeSelf = $("input[name=exportNode-includeSelf]").is(":checked"); 
        var includeNodeNames = $("input[name=exportNode-includeNodeNames]").is(":checked");
        var includePropertyNames = $("input[name=exportNode-includePropertyNames]").is(":checked");
        $.ajax({
            type: "GET",
            url: "/umbraco/backoffice/UmobitUtilities/ExportNodeDescendantsToExcel2?nodeId=" + nodeId + "&includeSelf=" + includeSelf + "&includeNodeNames=" + includeNodeNames + "&includePropertyNames=" + includePropertyNames ,
            data: {
            },
            success: function (result) {
                $("#loader").hide();
                if (result.success) {
                    var linkHtml = ' <div><a href="' + result.link + '">Click here to download</a></div>';
                    $("#result-box").addClass('success');
                    $("#result-box").html(result.message + linkHtml);
                }
                else {
                    $("#result-box").addClass('error');
                    $("#result-box").html(JSON.stringify(result.exceptions));
                }
            },
            error: function (result) {
                $("#loader").hide();
            }
        });
    });
    
</script>